/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poorlycodedbyafrench.bottezosselltotwitter.MainForm;

import com.poorlycodedbyafrench.bottezosselltotwitter.Core.Bot.GenericBotManager;
import com.poorlycodedbyafrench.bottezosselltotwitter.Core.Configuration.PanelRefreshInterface;
import com.poorlycodedbyafrench.bottezosselltotwitter.Misc.ButtonColumn;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.dv8tion.jda.api.entities.Guild;

/**
 *
 * @author david
 */
public class AllDiscordServerGenericBot extends javax.swing.JPanel implements PanelRefreshInterface {

    private MainBotForm mainBotForm;
    private DefaultTableModel model;

    /**
     * Creates new form AllDiscordServerGenericBot
     */
    public AllDiscordServerGenericBot() {
        initComponents();

        model = (DefaultTableModel) tbl_discord.getModel();

        Action leave = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {

                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                String guildToLeave = (String) table.getValueAt(table.getSelectedRow(), 1);

                int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to leave this discord : " + guildToLeave + " ?", "Warning", JOptionPane.YES_NO_OPTION);

                if (answer == JOptionPane.YES_OPTION) {
                    GenericBotManager.getGenericBotManager().removeGenericBot(guildToLeave);
                    GenericBotManager.getGenericBotManager().getGenericDiscord().getJda().getGuildById(guildToLeave).leave().queue();
                    ((DefaultTableModel) table.getModel()).removeRow(modelRow);
                }

            }
        };

        ButtonColumn buttonColumnDelete = new ButtonColumn(tbl_discord, leave, 2);
    }

    @Override
    public void refresh() {
        model.setRowCount(0);

        if (GenericBotManager.getGenericBotManager().getGenericDiscord() != null) {
            for (Guild g : GenericBotManager.getGenericBotManager().getGenericDiscord().getJda().getGuilds()) {
                model.addRow(new Object[]{g.getName(), g.getId(), "Leave"});
            }
        }

    }

    @Override
    public void setMainBotForm(MainBotForm mainBotForm) {
        this.mainBotForm = mainBotForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_discord = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lbl_title.setText("Discord servers");
        add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 24, -1, -1));

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 28, -1, -1));

        tbl_discord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Id", "Leave"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_discord);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 770, 110));

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.mainBotForm.swapView("genericBotMenu");
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        refresh();
    }//GEN-LAST:event_btn_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTable tbl_discord;
    // End of variables declaration//GEN-END:variables

}
