/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poorlycodedbyafrench.bottezosselltotwitter.MainForm;

import com.poorlycodedbyafrench.bottezosselltotwitter.Core.ApiRunnable.SalesToSocialNetwork;
import com.poorlycodedbyafrench.bottezosselltotwitter.Core.MarketPlaceClass.CallObjkt;
import com.poorlycodedbyafrench.bottezosselltotwitter.Core.SocialNetworkInterface.SocialNetworkInterface;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;
import com.poorlycodedbyafrench.bottezosselltotwitter.Core.MarketPlaceInterface.CallMarketPlaceInterface;
import com.poorlycodedbyafrench.bottezosselltotwitter.Core.SocialNetworkClass.TwitterSocialNetwork;
import javax.swing.JDialog;

/**
 * Main form of the application
 * @author david
 */
public class MainBotForm extends javax.swing.JFrame {

    /**
     * List of all tje marketplaces where we will find sales
     */
    private List<CallMarketPlaceInterface> marketplaces; 
    
    /**
     * List of all Social network where we will share information
     */
    private List<SocialNetworkInterface> socialNetworks; 
    
    /**
     * Table that contains the log
     */
    private DefaultTableModel model;
    
    /**
     * The thread that will call API 
     */
    private SalesToSocialNetwork apiHandler;
    
    /**
     * Tool that will execute query every hours
     */
    private ScheduledExecutorService executor;
    
    /**
     * Boolean used because we never stop the thread. And instead of starting the thread when we start the app, we create it at the fist click on "start" button. Then we have the first call
     */
    private boolean firststart;
    /**
     * Creates new form MainBotForm
     * Get the table as dataModel
     * Create social and maketplace object
     * Create the APIHandler and Executor
     */
    public MainBotForm() {
        initComponents();
        
        setStateComponent(true);
        
        model = (DefaultTableModel) tbl_status.getModel();
        model.setRowCount(0);
        
        marketplaces = new ArrayList<CallMarketPlaceInterface>();
        socialNetworks = new ArrayList<SocialNetworkInterface>();
        
        marketplaces.add(new CallObjkt());
        
        socialNetworks.add(new TwitterSocialNetwork());
              
        apiHandler = new SalesToSocialNetwork(model);
        
        executor = Executors.newScheduledThreadPool(1);
        
        firststart = true;
    }

    /**
     * Change the state of the component depending if the bot is running or not
     * @param stateStart 
     */
    private void setStateComponent(boolean stateStart){
        btn_start.setEnabled(stateStart);
        txt_objkt_contract.setEnabled(stateStart);
        pwd_twitter_public_consumer_key.setEnabled(stateStart);
        pwd_twitter_private_consumer_key.setEnabled(stateStart);
        pwd_twitter_public_key.setEnabled(stateStart);
        pwd_twitter_private_key.setEnabled(stateStart);
        
         btn_stop.setEnabled(!stateStart);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_objkt_contract = new javax.swing.JLabel();
        txt_objkt_contract = new javax.swing.JTextField();
        lbl_twitter_public_consumer_key = new javax.swing.JLabel();
        pwd_twitter_private_consumer_key = new javax.swing.JPasswordField();
        lbl_twitter_private_consumer_key = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_status = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        lbl_twitter_access_key = new javax.swing.JLabel();
        lbl_twitter_private_key = new javax.swing.JLabel();
        pwd_twitter_private_key = new javax.swing.JPasswordField();
        pwd_twitter_public_key = new javax.swing.JPasswordField();
        pwd_twitter_public_consumer_key = new javax.swing.JPasswordField();
        BTN_License = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_objkt_contract.setText("Contract");

        lbl_twitter_public_consumer_key.setText("Public consumer key");

        lbl_twitter_private_consumer_key.setText("Private consumer key");

        tbl_status.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MarketPlace", "Status", "Data"
            }
        ));
        jScrollPane1.setViewportView(tbl_status);

        jLabel1.setText("Request status");

        btn_start.setText("Start");
        btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_startMouseClicked(evt);
            }
        });

        btn_stop.setText("Stop");
        btn_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stopMouseClicked(evt);
            }
        });

        lbl_twitter_access_key.setText("Public Access Key");

        lbl_twitter_private_key.setText("Private Access Key");

        BTN_License.setText("Licenses");
        BTN_License.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_LicenseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_objkt_contract)
                            .addComponent(btn_start))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_stop)
                                .addGap(0, 70, Short.MAX_VALUE))
                            .addComponent(txt_objkt_contract))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_twitter_private_consumer_key)
                            .addComponent(lbl_twitter_public_consumer_key))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwd_twitter_private_consumer_key, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwd_twitter_public_consumer_key, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_License)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_twitter_private_key)
                            .addComponent(lbl_twitter_access_key))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwd_twitter_private_key, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwd_twitter_public_key, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_objkt_contract)
                    .addComponent(lbl_twitter_public_consumer_key)
                    .addComponent(txt_objkt_contract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_twitter_public_consumer_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd_twitter_private_consumer_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_twitter_private_consumer_key)
                    .addComponent(btn_start)
                    .addComponent(btn_stop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_twitter_access_key)
                    .addComponent(pwd_twitter_public_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd_twitter_private_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_twitter_private_key)
                    .addComponent(BTN_License))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbl_objkt_contract.getAccessibleContext().setAccessibleName("lbl_objkt_contract");
        txt_objkt_contract.getAccessibleContext().setAccessibleName("");
        lbl_twitter_public_consumer_key.getAccessibleContext().setAccessibleName("lbl_twitter_login");
        lbl_twitter_private_consumer_key.getAccessibleContext().setAccessibleName("lbl_twitter_password");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * We check value
     * If it's good, we change the state of component
     * Update data
     * and start the bot
     * @param evt 
     */
    private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_startMouseClicked
                
        if (checkvalue()) {
            setStateComponent(false);
            updateData();
            startloop(); 
        } 
    }//GEN-LAST:event_btn_startMouseClicked

    /**
     * We change the state of component
     * and we stop the bot
     * @param evt 
     */
    private void btn_stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stopMouseClicked
       setStateComponent(true);
       stoploop();
    }//GEN-LAST:event_btn_stopMouseClicked

    /**
     * Show the license window
     * @param evt 
     */
    private void BTN_LicenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_LicenseMouseClicked
        JDialog license = new JDialog();
        license.add(new LicenseBot());
        license.pack();
        license.setVisible(true);
    }//GEN-LAST:event_BTN_LicenseMouseClicked

    /**
     * Check if the field are fill
     * @return true if all data are correct, else wrong
     */
    private boolean checkvalue(){
        
        boolean isDataCorrect = true;
        
        if (txt_objkt_contract.getText().isBlank()){
            isDataCorrect = false;
        }
        
        if (new String(pwd_twitter_public_consumer_key.getPassword()).isBlank()){
            isDataCorrect = false;
        }
        
        if (new String(pwd_twitter_private_consumer_key.getPassword()).isBlank()){
            isDataCorrect = false;
        }
        
        if (new String(pwd_twitter_public_key.getPassword()).isBlank()){
            isDataCorrect = false;
        }
        
        if ( new String(pwd_twitter_private_key.getPassword()).isBlank()){
            isDataCorrect = false;
        }
        
        return isDataCorrect;
    }
    
    /**
     * Update the data of Marketplace and SocialNetwork
     */
    private void updateData(){
        for(CallMarketPlaceInterface oneMarkeplace : marketplaces){
            
            if (oneMarkeplace.getClass() == CallObjkt.class){
                CallObjkt objkt = (CallObjkt) oneMarkeplace;
                objkt.setContract(txt_objkt_contract.getText());
            }
        }
        
        for(SocialNetworkInterface oneSocialNetwork : socialNetworks){
            
            if (oneSocialNetwork.getClass() == TwitterSocialNetwork.class){
                TwitterSocialNetwork twitterSocialNetwork = (TwitterSocialNetwork) oneSocialNetwork;
                twitterSocialNetwork.instanceTwitter(new String(pwd_twitter_public_consumer_key.getPassword()), new String(pwd_twitter_private_consumer_key.getPassword()), new String(pwd_twitter_public_key.getPassword()), new String(pwd_twitter_private_key.getPassword()), txt_objkt_contract.getText());
            }
        }
        
        
        apiHandler.setMarketplaces(marketplaces);
        apiHandler.setSocialNetworks(socialNetworks);
    }
    
    /**
     * Start the bot
     * 
     */
    private void startloop(){
       if (firststart){
           executor.scheduleAtFixedRate(apiHandler, 0, 1, TimeUnit.HOURS);
           firststart = false;
       }
       
       apiHandler.setIsActive(true);
    }
    
    /**
     * Stop the bot
     */
    private void stoploop(){
        apiHandler.setIsActive(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBotForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_License;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_objkt_contract;
    private javax.swing.JLabel lbl_twitter_access_key;
    private javax.swing.JLabel lbl_twitter_private_consumer_key;
    private javax.swing.JLabel lbl_twitter_private_key;
    private javax.swing.JLabel lbl_twitter_public_consumer_key;
    private javax.swing.JPasswordField pwd_twitter_private_consumer_key;
    private javax.swing.JPasswordField pwd_twitter_private_key;
    private javax.swing.JPasswordField pwd_twitter_public_consumer_key;
    private javax.swing.JPasswordField pwd_twitter_public_key;
    private javax.swing.JTable tbl_status;
    private javax.swing.JTextField txt_objkt_contract;
    // End of variables declaration//GEN-END:variables
}
