/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poorlycodedbyafrench.bottezosselltotwitter.MainForm;

import com.poorlycodedbyafrench.bottezosselltotwitter.Core.Configuration.LogManager;
import com.poorlycodedbyafrench.bottezosselltotwitter.Core.Configuration.PanelRefreshInterface;
import com.poorlycodedbyafrench.bottezosselltotwitter.Core.GeneralStatistic.GeneralStatisticRefresher;
import java.awt.CardLayout;
import java.time.temporal.ChronoUnit;
import java.util.HashMap;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

/**
 * Main form of the application
 *
 * @author david
 */
public class MainBotForm extends javax.swing.JFrame {

    private CardLayout layoutManager;
    
    private HashMap<String, PanelRefreshInterface> allPanel;
    
    private transient ScheduledThreadPoolExecutor executor;

    private transient ScheduledFuture<?> scheduledStatRefresher;
    
    private transient GeneralStatisticRefresher apiStatisticRefresher;
    
    public MainBotForm() {
        initComponents();
        
        executor = (ScheduledThreadPoolExecutor) Executors.newScheduledThreadPool(1);
        executor.setRemoveOnCancelPolicy(true);
        
        apiStatisticRefresher = new GeneralStatisticRefresher();
        scheduledStatRefresher = executor.scheduleAtFixedRate(apiStatisticRefresher, 0, 10, TimeUnit.MINUTES);
        
        
        allPanel = new HashMap<>();
        
        allPanel.put("oneBotConfiguration", oneBotConfiguration);
        allPanel.put("licenseBot", licenseBot);
        allPanel.put("configurationMenu", configurationMenu);
        allPanel.put("marketPlaceProfileManagerAndCreator", marketPlaceProfileManagerAndCreator);
        allPanel.put("multipleBotMenu", multipleBotMenu);
        allPanel.put("socialNetworkProfileManagerAndCreator", socialNetworkProfileManagerAndCreator);
        allPanel.put("genericBotMenu", genericBotMenu);
        allPanel.put("allDiscordServerGenericBot", allDiscordServerGenericBot);
        allPanel.put("allTelegramServerGenericBot", allTelegramServerGenericBot);
        allPanel.put("adCompainMenu", adCompainMenu);
        
        for(PanelRefreshInterface aPanel : allPanel.values()){
            aPanel.setMainBotForm(this);
        }

        layoutManager = (CardLayout) mainPanel.getLayout();

        swapView("multipleBotMenu");
    }

    public void swapView(String keyCard) {
        layoutManager.show(mainPanel, keyCard);
        allPanel.get(keyCard).refresh();
        
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        oneBotConfiguration = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.OneBotConfiguration();
        licenseBot = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.LicenseBot();
        configurationMenu = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.ConfigurationMenu();
        marketPlaceProfileManagerAndCreator = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.MarketPlaceProfileManagerAndCreator();
        multipleBotMenu = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.MultipleBotMenu();
        socialNetworkProfileManagerAndCreator = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.SocialNetworkProfileManagerAndCreator();
        genericBotMenu = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.GenericBotMenu();
        allDiscordServerGenericBot = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.AllDiscordServerGenericBot();
        allTelegramServerGenericBot = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.AllTelegramServerGenericBot();
        adCompainMenu = new com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.AdCompainMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tezos sale bot manager");

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(oneBotConfiguration, "oneBotConfiguration");

        licenseBot.setName(""); // NOI18N
        mainPanel.add(licenseBot, "licenseBot");
        mainPanel.add(configurationMenu, "configurationMenu");
        configurationMenu.getAccessibleContext().setAccessibleName("");

        mainPanel.add(marketPlaceProfileManagerAndCreator, "marketPlaceProfileManagerAndCreator");
        mainPanel.add(multipleBotMenu, "multipleBotMenu");
        mainPanel.add(socialNetworkProfileManagerAndCreator, "socialNetworkProfileManagerAndCreator");
        socialNetworkProfileManagerAndCreator.getAccessibleContext().setAccessibleDescription("");

        mainPanel.add(genericBotMenu, "genericBotMenu");
        mainPanel.add(allDiscordServerGenericBot, "allDiscordServerGenericBot");
        allDiscordServerGenericBot.getAccessibleContext().setAccessibleName("");

        mainPanel.add(allTelegramServerGenericBot, "allTelegramServerGenericBot");
        allTelegramServerGenericBot.getAccessibleContext().setAccessibleDescription("");

        mainPanel.add(adCompainMenu, "adCompainMenu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            LogManager.getLogManager().writeLog(MainBotForm.class.getName(), ex);
        } catch (InstantiationException ex) {
            LogManager.getLogManager().writeLog(MainBotForm.class.getName(), ex);
        } catch (IllegalAccessException ex) {
            LogManager.getLogManager().writeLog(MainBotForm.class.getName(), ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            LogManager.getLogManager().writeLog(MainBotForm.class.getName(), ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBotForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.AdCompainMenu adCompainMenu;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.AllDiscordServerGenericBot allDiscordServerGenericBot;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.AllTelegramServerGenericBot allTelegramServerGenericBot;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.ConfigurationMenu configurationMenu;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.GenericBotMenu genericBotMenu;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.LicenseBot licenseBot;
    private javax.swing.JPanel mainPanel;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.MarketPlaceProfileManagerAndCreator marketPlaceProfileManagerAndCreator;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.MultipleBotMenu multipleBotMenu;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.OneBotConfiguration oneBotConfiguration;
    private com.poorlycodedbyafrench.bottezosselltotwitter.MainForm.SocialNetworkProfileManagerAndCreator socialNetworkProfileManagerAndCreator;
    // End of variables declaration//GEN-END:variables
}
